### ISSUE TITLE
Dependency management with bower

### ISSUE THREAD

**Issue by acorbi** [oceatoon/jquery.dynForm#1]
The library uses a series of js/css libraries which could be easily managed with http://bower.io.

**Comment by oceatoon** [comment]
sounds like a great plan
I've only seen bower work
haven't had a chance to play with it
let's do it !!

On Thu, Mar 26, 2015 at 4:00 PM, Alex Corbi notifications@github.com
wrote:

> The library uses a series of js/css libraries which could be easily
> managed with http://bower.io.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oceatoon/dynForm/issues/1.

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.
